export const legalSearchData = [
  {
    id: 1,
    title: "Contract Management",
    desc: "TLB has a dedicated contract lifecycle management services team that delivers customized solutions to law firms and corporates",
    learnMore: "/contractmanagement",
    image: "/legal-solutions/contract-management-card-bg.webp",
  },
  {
    id: 2,
    title: "Family Law Services",
    desc: "Outsourced family law services refer to the practice of engaging external professionals or organizations to provide family law-related services on behalf of individuals or entities. Instead of hiring in-house legal staff, outsourcing to TLB allows law firms or attorneys to access specialized expertise and resources.",
    learnMore: "/familylawservices",
    image: "/Family Law/pexels-kindel-media-7979431.jpg",
  },
  {
    id: 3,
    title: "Estate Planning",
    desc: "Estate Planning is necessary for every individual, irrespective of the value of their assets. We have resource pool with expertise in estate planning process",
    learnMore: "/estateplanning",
    image: "/legal-solutions/estate-planning-card-bg.webp",
  },
  {
    id: 4,
    title: "Immigration Support",
    desc: "Immigration involves movement of individuals from the country of their origin to the country of their preference, and is done with the help of immigration agency.",
    learnMore: "/globalimmigration",
    image: "/legal-solutions/immigration-card-bg.webp",
  },
  {
    id: 5,
    title: "Deposition Summary",
    desc: "Deposition summary is a key part of the inquiry procedure which takes place before the court proceedings",
    learnMore: "/depositionsummaryservices",
    image: "/legal-solutions/deposition-summary-card-bg.webp",
  },
  {
    id: 6,
    title: "Legal Research",
    desc: "TLB's team can help you in providing accurate solutions, analyze statutes and case studies to ensure that all your legal issues are taken care of accordingly.",
    learnMore: "/legalresearch",
    image: "/legal-solutions/legal-research-card-bg.webp",
  },
  {
    id: 7,
    title: "Litigation Support",
    desc: "The Legal Base has a dedicated pool of resources that can review huge volumes of documents within the stipulated deadlines and a competitive budget.",
    learnMore: "/litigationsupport",
    image: "/legal-solutions/litigation-support-card-bg.webp",
  },
  {
    id: 8,
    title: "Document Review",
    desc: "Outsourced paralegal services involve contracting with a third-party provider like TLB to handle various legal support tasks and responsibilities typically performed by in-house paralegals. TLB is a specialized firm that employ paralegals with expertise in different areas of law.",
    learnMore: "/manageddocumentreviewservice",
    image: "/legal-solutions/document-review-card-bg.webp",
  },
  {
    id: 9,
    title: "Case Intake Services",
    desc: "TLB is a leading legal intake service provider and has helped several attorneys and practices grow their businesses and be successful in the competitive marketplace. We provide high-quality legal intake solutions that are customised to your exact needs and requirements.",
    learnMore: "/caseintakeservices",
    image: "/Case Intake/pexels-mohamed-hamdi-16282318.jpg",
  },
  {
    id: 10,
    title: "Paralegal Services",
    desc: "Outsourced paralegal services involve contracting with a third-party provider like TLB to handle various legal support tasks and responsibilities typically performed by in-house paralegals. TLB is a specialized firm that employ paralegals with expertise in different areas of law.",
    learnMore: "/paralegalservices",
    image: "/Paralegal Services/pexels-dominika-roseclay-3839649.jpg",
  },
  {
    id: 11,
    title: "Personal Injury",
    desc: "Outsourced personal injury support services involve engaging third-party providers like TLB to assist law firms and attorneys in handling various tasks and responsibilities related to personal injury cases. ",
    learnMore: "/personalinjury",
    image: "/legal-solutions/personal-injury-card-bg.webp",
  },
  {
    id: 12,
    title: "Global IP Research & Consultation",
    desc: "TLB has a dedicated team of paralegals that can help you with a wide range of paralegal services, including legal research, drafting, and document review.",
    learnMore: "/globalipresearchandconsultationservices",
    image: "/Legal Research/pexels-lukas-317355.jpg",
  },
  {
    id: 13,
    title: "M_A Diligence Services",
    desc: "TLB has a dedicated team of paralegals that can help you with a wide range of paralegal services, including legal research, drafting, and document review.",
    learnMore: "/madiligenceservices",
    image: "/Legal Research/pexels-anna-shvets-5324926.jpg",
  }
];
